services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - pgnetwork

  taxi_ingest:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    environment:
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - HOST=pgdatabase
      - PORT=5432
      - DB=${POSTGRES_DB}
      - TABLE_NAME=yellow_taxi_trips
      - URL=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz
    networks:
      - pgnetwork
    depends_on:
      - pgdatabase
    container_name: taxi_ingest

networks:
  pgnetwork:
    name: pgnetwork
    driver: bridge
